### ISSUE TITLE
Add alternative npx command

### ISSUE THREAD

**Issue by stefnotch** [neutralinojs/neutralinojs.github.io#101]
It'd be quite neat if this site https://neutralino.js.org/docs/#/tools/cli also had an `npx` command like `npx @neutralinojs/neu create amazon-widget-generator --template <templateName>`. Then, the end user wouldn't have to globally install the neutralino CLI when trying it out for the first time.

**Comment by shalithasuranga** [comment]
Hey.. I am closing this issue because there is only one template with v2. Especially, that template has no package.json. Please check https://neutralino.js.org/docs/developer-environment/project-structure
