### ISSUE TITLE
quickstart url 404

### ISSUE THREAD

**Issue by fanfare** [neutralinojs/neutralinojs.github.io#110]
the link to 'my first app' at the very bottom of this page https://github.com/neutralinojs/neutralinojs.github.io/blob/master/docs/gettingstarted/quickstart.md points to a 404 page.

**Comment by shalithasuranga** [comment]
Could you please try web version here https://neutralino.js.org/docs/#/

**Comment by fanfare** [comment]
oh i see - my mistake - i was using the actual github readme to view the documentation.
