### ISSUE TITLE
Website completely white using ublock origin.

### ISSUE THREAD

**Issue by 1337cookie** [neutralinojs/neutralinojs.github.io#114]
The website is completely blank when using ublock origin. If it's intentional you should let users know.

**Comment by shalithasuranga** [comment]
Hey... Thanks for letting us know. will look about it. Not sure it's related to ethical ads integration. Could you please try `ethicalads` on your unlock environment and let me know the output. That will help us to solve this issue.

**Comment by 1337cookie** [comment]
If I bring up the devtools console there is already some errors present. 
`ReferenceError: ethicalads is not defined
    at c4f5d8e4.162d7f7b.js:1
    at ju (main.34db2d99.js:2)
    at t.unstable_runWithPriority (main.34db2d99.js:2)
    at Ga (main.34db2d99.js:2)
    at Lu (main.34db2d99.js:2)
    at gu (main.34db2d99.js:2)
    at main.34db2d99.js:2
    at t.unstable_runWithPriority (main.34db2d99.js:2)
    at Ga (main.34db2d99.js:2)
    at Va (main.34db2d99.js:2)
ll @ main.34db2d99.js:2
`

**Comment by shalithasuranga** [comment]
Thank you very much. I will apply a fix asap

**Comment by shalithasuranga** [comment]
It is fixed.. Hope you can see the website properly.
