### ISSUE TITLE
Update committers list

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#138]
Add https://github.com/corbane

**Comment by RaviTejaVattem** [comment]
I want to work on this issue.

Do I need to add https://github.com/corbane to the committer's list in app??

![image](https://user-images.githubusercontent.com/43704759/135753544-6146277b-0dd4-4e22-b8cb-ce7d75cdf858.png)

Is this the file I need to change ?? 
docs/community/committers.md

**Comment by shalithasuranga** [comment]
Hey.. @RaviTejaVattem . Yeah, great. that's the place to be modified. Please use name and link to Github Similar to other entries :)

**Comment by RaviTejaVattem** [comment]
Thanks for the confirmation, I will work on this.

Can you assign this issue to me?

**Comment by shalithasuranga** [comment]
Yeah sure Thanks @RaviTejaVattem
