### ISSUE TITLE
Typos and improvements: Hacktoberfest 2021

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#140]
The official website and docs can contain some typos and spelling issues. If you found such issues, please make a pull request. This issue is especially for contributors who are participating in Hacktoberfest 2021.

Note: More than one contributor may work on this issue :)

**Comment by jonbrohauge** [comment]
Hi @shalithasuranga 
I'd like to look at this issue as well.

**Comment by shalithasuranga** [comment]
Hey.. Thanks to all who contributed this repo during Hacktoberfest!
