### ISSUE TITLE
Please Rewrite the Docs and include more examples.

### ISSUE THREAD

**Issue by alixsep** [neutralinojs/neutralinojs.github.io#150]
Neutralino.js is great! but unfortunately the docs are extremely poor written. I would like to see:

1. A much better written docs
2. A part of the doc that explains source code and how it works

As result, 1 will only lead to more people getting into using neutralino and 2 will make contributing much easier!

**Comment by shalithasuranga** [comment]
Hey.. all thanks for reporting and discussing this. I've created https://github.com/neutralinojs/neutralinojs.github.io/issues/151 to specially for all these points you've mentioned. Also, please note that we've already updated the documentation with the most required info. Eg Quick intro to the native API: https://neutralino.js.org/docs/api/overview
