### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#151]
- Identify places where the content is not enough and improve 
- Go through the tutorial flow and restructure if needed
- Add more details about browser and cloud mode 
- Update main repo's README with some intro to source code

**Comment by NethmiRodrigo** [comment]
Hi @shalithasuranga! Can I be assigned to this and update the docs starting with the framework developer guide?

**Comment by shalithasuranga** [comment]
Hey.. @NethmiRodrigo Feel free to submit pull requests for the above points -- I will keep this unassigned since this is a more generic issue to track down many things. Please create specific issues if needed

**Comment by NethmiRodrigo** [comment]
> 

Will do! Thank you!
