### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#171]
https://neutralino.js.org/docs/api/overview/ has some broken links

**Comment by pathange-s** [comment]
@shalithasuranga May I work on this issue ? Assign me.

**Comment by shalithasuranga** [comment]
Sure, Thanks for the support. I assigned you to the issue as you've requested :) Please let me know here if you have questions. I just found some broken links in https://neutralino.js.org/docs/api/overview/ perhaps, there can be some broken links in other pages as well :)

**Comment by pathange-s** [comment]
Going through the docs as a part of understanding the framework. Will surely report any bugs, broken links, and UI fixes.

**Comment by pathange-s** [comment]
@shalithasuranga Also, the order of links in the menu and in the page are jumbled. Is there any reason why it is this way ?

![untitled (1)](https://user-images.githubusercontent.com/76244077/157447192-dd5dc116-5246-4155-a2ab-c4a0a87fe3ed.png)

**Comment by pathange-s** [comment]
Sure ! On it !
