### ISSUE TITLE
Encountered a broken link

### ISSUE THREAD

**Issue by Jassi10000** [neutralinojs/neutralinojs.github.io#174]
![image](https://user-images.githubusercontent.com/64856348/157673676-f568fbc2-1c75-4d2e-9d27-1e89a5075321.png)

On clicking on " here " , the page redirects to 404

If one of the maintainers can provide me the correct link , then I would love to contribute to this issue

**Comment by shalithasuranga** [comment]
Hello.. Thanks for reporting this issue. I think if you remove the trailing `/` from the current URL, the circled link will work and you can find the correct link.

**Comment by shalithasuranga** [comment]
If the above workaround didn't work, please consider the link as https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app/

**Comment by Jassi10000** [comment]
> Hello.. Thanks for reporting this issue. I think if you remove the trailing `/` from the current URL, the circled link will work and you can find the correct link.

This doesn't works, leme try the other one

**Comment by Jassi10000** [comment]
> If the above workaround didn't work, please consider the link as https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app/

Can I contribute to this issue by putting the right url in the docs, can you please assign this to me

**Comment by shalithasuranga** [comment]
Sure @Jassi10000 . I've assigned you as you requested :) Thanks for contributing :tada:

**Comment by Jassi10000** [comment]
> Sure @Jassi10000 . I've assigned you as you requested :) Thanks for contributing 🎉

Thank you sir !!! 😃

**Comment by shalithasuranga** [comment]
I am closing this one since the broken issue is resolved. We can open a new issue if we detect another issue related to broken links
