### ISSUE TITLE
Broken Link on Page: Your First NeutralinoJs App

### ISSUE THREAD

**Issue by Jassi10000** [neutralinojs/neutralinojs.github.io#176]
![image](https://user-images.githubusercontent.com/64856348/157703378-9c938e12-8ec0-41dc-80f0-78dfa0c502ee.png)

Just like #174 , here also on the page
https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app/

I found another broken link, @shalithasuranga please assign me this as well , will correct this too

Also please share the correct link that the page should redirect to

**Comment by Jassi10000** [comment]
@shalithasuranga Sir the same issue lies on this page as well 
Pls assign this to me , so that I can correct this one too

**Comment by shalithasuranga** [comment]
Hey @Jassi10000 Can we close this issue since it has already been fixed by you? 

Thanks

**Comment by Jassi10000** [comment]
> Hey @Jassi10000 Can we close this issue since it has already been fixed by you?
> 
> Thanks

Sir this issue is valid , since this issue is the same as the previous one but is present on some another page as well

**Comment by shalithasuranga** [comment]
Sure.. Thanks for checking. Feel free to submit a pull request if you found some broken links.. Please make sure to use the relative markdown file :)

**Comment by Jassi10000** [comment]
> Sure.. Thanks for checking. Feel free to submit a pull request if you found some broken links.. Please make sure to use the relative markdown file path which will work on GitHub too :)

Sure sir

**Comment by Jassi10000** [comment]
@shalithasuranga Sir I don't think the issue still persists as someone maybe in the core team has already made the changes
So am closing the issue now
