### ISSUE TITLE
A lil suggestion for the documentation on making a react cum Neutralino app

### ISSUE THREAD

**Issue by Jassi10000** [neutralinojs/neutralinojs.github.io#184]
@shalithasuranga 
While making a React and Neutralino Application , I got into trouble due to this 

![image](https://user-images.githubusercontent.com/64856348/160149894-0d66979e-c4e2-4662-a90b-99d2eb545319.png)

Here the patch file indicates that the <code>index.html</code> lies in the <code>"/litepy-react/public/index.html"</code>

But if I look in the starting parts of documentation on this page , the command which asks to create a new react app , there the project name is <code> myapp-react </code> 

![image](https://user-images.githubusercontent.com/64856348/160150343-f0ebba03-9993-4905-8653-3bd0dea880a8.png)

## This may not seem a big issue but as a beginner like me will definitely encounter this problem and will face the error like I faced , which is not good ,so want to request the maintainer to please assign me this issue so that I can update the folder name in the last command to 

``` 
  "cli": {
    // --- other options
    "frontendLibrary": {
        "patchFile": "/myapp-react/public/index.html",
        "devUrl": "http://localhost:3000"
    }
  }
}

```

The earlier version is as below :  

```
  "cli": {
    // --- other options
    "frontendLibrary": {
        "patchFile": "/litepy-react/public/index.html",
        "devUrl": "http://localhost:3000"
    }
  }
}

```

**Comment by Jassi10000** [comment]
@shalithasuranga Sir can you please look into this issue and pls assign me so that I can improve the docs

**Comment by pathange-s** [comment]
Heyy ! I see that Shalithasuranga has been a little busy since last few days. Also this PR seems like just a one line fix. Why not you drop a PR and wait for it to get merged ?

**Comment by Jassi10000** [comment]
> Heyy ! I see that Shalithasuranga has been a little busy since last few days. Also this PR seems like just a one line fix. Why not you drop a PR and wait for it to get merged ?

Sure sir , no issues 
Thanks for telling

**Comment by shalithasuranga** [comment]
Hey all.. looks like this issue was fixed already.. Closing the issue :tada:
