### ISSUE TITLE
Add missing CLI arguments to the docs

### ISSUE THREAD

**Issue by NethmiRodrigo** [neutralinojs/neutralinojs.github.io#190]
Some of the internal CLI arguments present in the framework is missing in the [internal CLI arguments page](https://neutralino.js.org/docs/cli/internal-cli-arguments/)

**Comment by NethmiRodrigo** [comment]
@shalithasuranga Can I work on this issue?

**Comment by shalithasuranga** [comment]
Hey @NethmiRodrigo sure.. Thanks :tada:

**Comment by NethmiRodrigo** [comment]
Hey @shalithasuranga shall I close this issue since the PR is merged? :)

**Comment by pathange-s** [comment]
Yes, you can ! 🎉
