### ISSUE TITLE
Bug: A redirection issue on the extensions docs

### ISSUE THREAD

**Issue by Jassi10000** [neutralinojs/neutralinojs.github.io#197]
On this page 
https://neutralino.js.org/docs/api/extensions/

When I click on this link
![image](https://user-images.githubusercontent.com/64856348/163141522-5d61cb58-19c8-4bbd-bbd4-38687661bca7.png)

I get this 
![image](https://user-images.githubusercontent.com/64856348/163141575-9b13c4d8-2e0e-4427-8fbf-27747e9b438a.png)

I am working on this one and will sending a PR soon

**Comment by pathange-s** [comment]
Suggestion, make sure to have proper Title for issues / pull requests.

**Comment by Jassi10000** [comment]
> Suggestion, make sure to have proper Title for issues / pull requests.

Is it good now ? 😊

**Comment by pathange-s** [comment]
Yea, also was suggesting not to have sms language.
I suggested having proper commit messages, but I was told that [ReleaseZRI](https://github.com/codezri/releasezri) is used to generate releases, so better keep simple message conveying titles.

**Comment by shalithasuranga** [comment]
Hey all.. I am closing this one since the link works okay right now. Thanks :tada:
