### ISSUE TITLE
Inconsistency in client library project structure documentation

### ISSUE THREAD

**Issue by Ayman161803** [neutralinojs/neutralinojs.github.io#209]
There is no ``src/debug`` within the [Neutralino.js](https://github.com/neutralinojs/neutralino.js) repository as mentioned on the website [here](https://neutralino.js.org/docs/contributing/framework-developer-guide/#client-library). Do correct me if I am wrong.

### Possible Fixes
- Replace ``src/debug`` with ``src/api/debug``.
- Remove ``src/debug`` from the list.

Will send a PR depending on what seems preferrable

**Comment by pathange-s** [comment]
Yes. The documentation previously had the directory `src/debug`. With counting time, it was removed. I guess you can go ahead making a PR for the same and wait for Shalitha to give it a review.
