### ISSUE TITLE
How about adding docsearch

### ISSUE THREAD

**Issue by cmgchess** [neutralinojs/neutralinojs.github.io#220]
How about adding search into the docs. Can be useful as the doc grows

Adding docsearch seems pretty straightforward
https://docusaurus.io/docs/search#using-algolia-docsearch states that open source projects can apply for a free API key and scheduled scraping+indexing.

Here is what I got from a manual indexing
https://neutralinojs-github-io.vercel.app/

**Comment by pathange-s** [comment]
Great mann ! Thought of this long back but didn't put any step forward. 
@shalithasuranga seems like this is must !

**Comment by shalithasuranga** [comment]
Hey @cmgchess and @pathange-s Thanks this is a great idea, I will get an API key with Neutralinojs email and add the search feature soon :tada:

**Comment by pathange-s** [comment]
@shalithasuranga any updates on this man? Reminding in case you forgot.

**Comment by viralgupta** [comment]
hey @shalithasuranga any update on algolia doc search api key?
