### ISSUE TITLE
Changing the UI 

### ISSUE THREAD

**Issue by harshit-dugar** [neutralinojs/neutralinojs.github.io#221]
On the main page of https://neutralino.js.org , Build once with javascript part is incorrectly placed and the additional area is taking a large space making the UI feel low.

**Comment by harshit-dugar** [comment]
@shalithasuranga Should I make these changes

**Comment by pathange-s** [comment]
Well, you can drop a pull request with those changes. We will review it.
COming to the spelling mistake, you mean the capital S in `Javascript` ? Go forward. Additional area below it ? Yes, makes feel UI-less. What changes do you have in store for these ?

**Comment by pathange-s** [comment]
The setup is simple.
https://github.com/neutralinojs/neutralinojs.github.io clone this repository. then `yarn install` and `yarn start`.
Make any changes to any files in the cloned repo, and start the server to see the changes. Hence you can test it.

**Comment by harshit-dugar** [comment]
@pathange-s please checkout the pull request #223

**Comment by harshit-dugar** [comment]
@pathange-s  now there is no change in yarn.lock in new pull request #225

**Comment by pathange-s** [comment]
Reviewed it mann. Looks better. Checkout my comments on the pull request.

**Comment by harshit-dugar** [comment]
@pathange-s Done with it

**Comment by shalithasuranga** [comment]
Closing this since the related PR was merged. Thanks, everyone :tada:
