### ISSUE TITLE
Helper Guide for new contributors to neutralinojs.

### ISSUE THREAD

**Issue by pathange-s** [neutralinojs/neutralinojs.github.io#226]
- [ ] Create a new section in docs `Framework Contributors Guide`, with resources specific to new contributors. 
- [ ] Update `Framework developers Guide` to keep it specific to developers.
- [ ] Update the two core repositories - [Neutralinojs](https://github.com/neutralinojs/neutralinojs), [Neutralinojs CLI](https://github.com/neutralinojs/neutralinojs-cli) and [Neutralino.js](https://github.com/neutralinojs/neutralino.js) with `Contributing.md`, `CodeOfConduct.md` and necessary readme & documentation changes.

**Comment by pathange-s** [comment]
@shalithasuranga please label this issue under documentation and enhancement.

**Comment by dbmohit** [comment]
can i work on this?

**Comment by sahil-1729** [comment]
is anyone working on this issue?

**Comment by tanishkagupta27** [comment]
@shalithasuranga I want to work on this issue.

**Comment by shalithasuranga** [comment]
We can close this issue since now we have a good guidance page on the official documentation and other files mentioned in this issue. Thanks so much for creating this issue and showing your interest regarding this task :tada:
