### ISSUE TITLE
Small typo in configuration modes documentation.

### ISSUE THREAD

**Issue by pawankm21** [neutralinojs/neutralinojs.github.io#231]
In [docs/configuration/modes/#cloud](https://neutralino.js.org/docs/configuration/modes/#cloud) the text says

_Besides, **you can the Neutralinojs** server on bare-metal servers, virtual machines, and application containers as a lightweight message broker. You may find endless use-cases for this framework mode._

**Comment by shalithasuranga** [comment]
Closing this since it's fixed. Thank you very much for reporting this :)
