### ISSUE TITLE
A section for tooling/templates

### ISSUE THREAD

**Issue by ernest-rudnicki** [neutralinojs/neutralinojs.github.io#239]
**Expected behaviour**
Neutralinojs website should have a section for templates/tooling. Having this section would allow other developers to see what tools are available for neutralinojs that could speed up their development process.

**Actual behaviour**
There is no such section right now.

**Comment by AFZL210** [comment]
Hey! i'm beginner and if this issue is open i would love to work on it

**Comment by Maykkkk** [comment]
@ernest-rudnicki  hey, I want to work on this issue assign me

**Comment by ernest-rudnicki** [comment]
@Maykkkk I am not able to assign you, but you can create a Draft PR add a comment here with a mention of PR id

**Comment by devanshkansagra** [comment]
Heyy, Can you tell where this section is to be kept??

**Comment by shalithasuranga** [comment]
Closing this since now we have a new page: https://neutralino.js.org/resources/

Thanks :tada:
