### ISSUE TITLE
Neutralino.os.showNotification kills explorer.exe on Windows 11

### ISSUE THREAD

**Issue by faulander** [neutralinojs/neutralinojs.github.io#249]
Latest Version,
local development,
Windows 11.

**Code:**
```
function onWindowClose() {
    Neutralino.app.exit();
}

Neutralino.init();
Neutralino.os.showNotification("JSH", "JSH running in background!", "INFO")

```

**Error logged:**
```
Name der fehlerhaften Anwendung: explorer.exe, Version: 10.0.22621.885, Zeitstempel: 0xbff9bd74
Name des fehlerhaften Moduls: Taskbar.dll, Version: 10.0.22621.885, Zeitstempel: 0x00d9003c
Ausnahmecode: 0xc0000005
Fehleroffset: 0x000000000015a9d4
ID des fehlerhaften Prozesses: 0x0x4244
Startzeit der fehlerhaften Anwendung: 0x0x1D8F50664BEDAE5
Pfad der fehlerhaften Anwendung: C:\WINDOWS\explorer.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\Taskbar.dll
Berichtskennung: b71f0f3f-4ca2-4a75-af63-e4caf62bc3f8
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by DaanishShaikh** [comment]
what happens if you comment out the line Neutralino.os.showNotification("JSH", "JSH running in background!", "INFO")
does the error go away??
also can you please explain this issue in more detail??

**Comment by shalithasuranga** [comment]
Closing this since it doesn't happen on Windows and the notification implementation works fine for other developers. Perhaps, this is something related with an antivirus guard :)

**Comment by DaanishShaikh** [comment]
> Closing this since it doesn't happen on Windows and the notification implementation works fine for other developers. Perhaps, this is something related with an antivirus guard :) Thanks for reporting this and starting a discussion

welcome!
