### ISSUE TITLE
Is it possible to use browser mode instead of cloud mode but use it like you're example here

### ISSUE THREAD

**Issue by Kali95739** [neutralinojs/neutralinojs.github.io#255]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://medium.com/neutralinojs/getting-started-with-neutralinojs-cloud-preview-version-aws-ec2-6e618d8a2ddb&ved=2ahUKEwipmJD099_4AhXiJX0KHXoADvcQFnoECBQQAQ&usg=AOvVaw1W1orlAWFsYlA1qjJCDZMq for your article here showing how to use cloud mode online is it possible to do the same with browser mode? Instead

**Comment by shalithasuranga** [comment]
Hello @Kali95739, the browser mode works only for the local computer and the cloud mode exposes the Neutralinojs app to the whole network (if the port is not blocked via your network firewall). So, if you host your app on AWS, you will always have to use the cloud mode :tada:
