### ISSUE TITLE
Couldn't find webpages for content on click of links

### ISSUE THREAD

**Issue by Deepu178** [neutralinojs/neutralinojs.github.io#266]
I couldn't find any content when I click on these links 
"neutralino.config.json
Project structure
neu CLI
Global variables
Application modes
Native API overview
" in https://neutralino.js.org/docs/getting-started/your-first-neutralinojs-app/ 
page
so I'm looking forward to fix this issue.
<img width="861" alt="Screenshot_20230121_194804" src="https://user-images.githubusercontent.com/68677868/213871339-258f59f8-c0ab-4c83-8177-e4274cdf8290.png">

<img width="741" alt="Screenshot_20230121_194739" src="https://user-images.githubusercontent.com/68677868/213871344-dc6c5888-7d5a-4cfe-b1b9-136085d91a95.png">

<img width="879" alt="Screenshot_20230121_194715" src="https://user-images.githubusercontent.com/68677868/213871353-21b0ce27-895d-4723-96ea-105053a82462.png">

Thanks!

**Comment by keshavkumarhembram** [comment]
@Deepu178  I checked those links. The links are working correctly.

**Comment by Deepu178** [comment]
@keshavkumarhembram It's working fine now but at that time
links were not working.

**Comment by keshavkumarhembram** [comment]
> 

ok
