### ISSUE TITLE
Feature Proposal: Copying npm install Command to Clipboard

### ISSUE THREAD

**Issue by sarcaxticlarka** [neutralinojs/neutralinojs.github.io#287]
Objective:
To improve user experience and streamline the process of installing NeutralinoJS by adding a "Copy to Clipboard" feature for the installation command on the website.

Feature Description:
Currently, users need to manually copy and paste the installation command (npm install -g @neutralinojs/neu) to their terminal. This proposal suggests adding a clickable icon next to the installation command, which, when clicked, automatically copies the command to the user's clipboard. Additionally, a notification message will be displayed to inform the user that the text has been successfully copied.

Implementation Steps:

- Integrate a clickable icon, strategically placed for user accessibility.

- Implement the necessary code to copy npm install -g @neutralinojs/neu to the user's clipboard.

- Include a notification message to inform the user that the text has been successfully copied.

 Benefits:

- Enhanced User Convenience: Users can quickly copy the installation command with a single click, reducing the chances of manual errors.

- Streamlined Installation: This feature simplifies the installation process, especially for users who may not be familiar with the command.

Request:
I am enthusiastic about contributing to the development of this feature and would like to request the assignment to work on its implementation. As a user of the platform, I believe this addition will be highly beneficial, and I am committed to ensuring its seamless integration.

**Comment by shalithasuranga** [comment]
Hello @sarcaxticlarka, thanks for posting this feature request and letting us know about your preference about contributing to this issue. Yeah, your idea will improve developer productivity since they can get started with Neutralinojs CLI faster. Please continue contributing this feature with a pull request :) 

Implementation note: It seems that we can take this feature directly from Docusaurus. Please check this issue: https://github.com/facebook/docusaurus/issues/6185

Thanks :tada:

**Comment by skushagra9** [comment]
Hey, I am interested to solve this issue, please assign to me

**Comment by skushagra9** [comment]
Its already implemented here,
if anything else please let me know
![image](https://github.com/neutralinojs/neutralinojs.github.io/assets/120712705/dcb1b6c5-551a-43b2-a656-5b6cadaa18d9)

**Comment by shalithasuranga** [comment]
Closing this since the issue was fixed already. Thanks all :tada:
