### ISSUE TITLE
Update the resources page with more items

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#295]
The goal is to update this page: https://neutralino.js.org/resources/, 

Using the following sources:

- https://github.com/neutralinojs-community/awesome-neutralino
- https://github.com/achou11/awesome-neutralino
- By searching Goolgle, GitHub, and other sources

Note: Please add a note and give credits for sources. Contributors may submit multiple pull-requests for this issue...

**Comment by skushagra9** [comment]
I am interested to work on this

**Comment by its-VinayKumar** [comment]
@shalithasuranga Plz Assign me this issue I want work on this and I will make the PR as soon as possible.

**Comment by 97Clinton** [comment]
@shalithasuranga please assign this issue to me, I have gone through it all and I think I have figured out a way to resolve the issue and update the page. Will deliver on time.

**Comment by tanishkagupta27** [comment]
@shalithasuranga I want to work on this issue. Please assign me.

**Comment by Shubham071122** [comment]
hey @shalithasuranga can you explain more about this what actully the error is?

**Comment by PranavBarthwal** [comment]
@shalithasuranga I can work on this issue, please assign this to me.

**Comment by shalithasuranga** [comment]
Closing this since now the website has a well-structured resources page with several items, but feel free to add more items via new PRs. Thanks all :tada:
