### ISSUE TITLE
Update the documentation with the build scripts community project

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#299]
https://github.com/hschneider/neutralino-build-scripts

This community project lets you create platform-specific app bundles (not setup files). We can update the official documentation by explaining how to use this tool to create platform-specific app bundles.

We can add new content into this location: https://neutralino.js.org/docs/distribution/overview#creating-a-portable-application-package

**Comment by srajan07** [comment]
> https://github.com/hschneider/neutralino-build-scripts
> 
> This community project lets you create platform-specific app bundles (not setup files). We can update the official documentation by explaining how to use this tool to create platform-specific app bundles.
> 
> We can add new content into this location: https://neutralino.js.org/docs/distribution/overview#creating-a-portable-application-package

can you help to understand this   @@project?
