### ISSUE TITLE
Setup of other frontend framework then react is not added in Getting start guide

### ISSUE THREAD

**Issue by khushhalgarg112** [neutralinojs/neutralinojs.github.io#303]
In documentation there is no detail or mentions regarding how anyone can setup their project with vite, angular and vue.js ? This is creating problem while setting up the project.

**Comment by shalithasuranga** [comment]
Hello @khushhalgarg112, thanks so much for reporting this issue. The documentation ([this page](https://neutralino.js.org/docs/getting-started/using-frontend-libraries)) demonstrates how to setup Neutralinojs with any frontend framework by showing an example with React. You can use the same approach with any frontend framework. However, we'll create official templates for more frontend frameworks in the future :tada:
