### ISSUE TITLE
Migrate this project to Docusaurus 3.0

### ISSUE THREAD

**Issue by shalithasuranga** [neutralinojs/neutralinojs.github.io#308]

**Comment by PayalKumari10** [comment]
Please provide me details so I can solve this problem. @shalithasuranga

**Comment by shalithasuranga** [comment]
Hello @PayalKumari10, thanks for the interest, here we need to update the Dcusaurus package to 3.x, update other dependencies, and make sure the project works fine on latest Node runtime versions :)

**Comment by viralgupta** [comment]
hi @shalithasuranga, I am working on this issue, could you please assign this to me?

**Comment by shalithasuranga** [comment]
Done @viralgupta, Thanks for your interest :tada: regarding this issue

**Comment by shalithasuranga** [comment]
This task was completed by @viralgupta. Thanks :tada:
