### ISSUE TITLE
Add "Copy to Clipboard" Button for Enhanced Developer Experience

### ISSUE THREAD

**Issue by PranavBarthwal** [neutralinojs/neutralinojs.github.io#318]
### Overview:
The purpose of this issue is to propose the addition of a "Copy to Clipboard" button next to the "npm install -g @neutralinojs/neu" text to enhance the developer and user experience.

### Proposal:
I've made changes to include a "Copy to Clipboard" button. This feature aims to streamline the process of copying code snippets.

### Implementation Details:
- The "Copy to Clipboard" button will be strategically placed next to the relevant code snippet.
- Upon clicking the button, the corresponding content will be copied to the user's clipboard, allowing for easy pasting into other documents, code editors, or communication channels, and an alert will be displayed on the user's screen saying "Copied to Clipboard!"
- The implementation will be done using standard web technologies such as HTML, CSS, JavaScript, MaterialUI Icons, and react-copy-to-clipboard package ensuring compatibility across different browsers and platforms.

### Benefits:
- **Improved Developer Productivity:** Developers will no longer need to manually select and copy code snippets, saving time and reducing the risk of errors.
- **Enhanced User Experience:** Users will have a more seamless experience when interacting with our project, as they can quickly copy important information with just one click.

### Screenshots Of Proposed Changes:
![Screenshot (203)](https://github.com/neutralinojs/neutralinojs.github.io/assets/110532770/17302e2d-a04b-4db4-8091-8086634bf88f)

### Working Video: 
https://github.com/neutralinojs/neutralinojs.github.io/assets/110532770/f8aa1964-b863-438f-9157-81fff34d9de7

**Comment by PranavBarthwal** [comment]
@shalithasuranga Kindly check over this PR.

**Comment by shalithasuranga** [comment]
Closing this since the issue was fixed. Thanks everyone :tada:
