### ISSUE TITLE
[Bug] :  style issue : cannot see the text of npm install for library due to text color in light mode

### ISSUE THREAD

**Issue by Adityajparmar37** [neutralinojs/neutralinojs.github.io#327]
# ScreenShort of issue: 

![image](https://github.com/neutralinojs/neutralinojs.github.io/assets/105008414/fa114878-55b9-43c5-9ee1-af22bdb37ac4)

# Change to be made

- Change the color of text  in white/light mode

**Comment by sahith-ch** [comment]
is the issue still open?

**Comment by shubhiscoding** [comment]
Can I work on this?

**Comment by viralgupta** [comment]
duplicate of #321

**Comment by shalithasuranga** [comment]
Closing as a duplicate of #321. Thanks everyone :tada:
