### ISSUE TITLE
fix typo trasparent

### ISSUE THREAD

**Issue by halllo2** [neutralinojs/neutralinojs.github.io#329]
Can't find a way to create a pull request, so therefore this issue. In line 233 of docs/configuration/neutralino.config.json.md, trasparent needs to be replaced with transparent.

**Comment by Harshinireddy05** [comment]
Hey @halllo2 can you please assign this to me?

**Comment by halllo2** [comment]
Only someone with write access can assign issues.

**Comment by Kira6381** [comment]
> Hey @halllo2 can you please assign this issue to me? I would like to solve it.

Since noone is working on it you can get started with it and raise a PR.

**Comment by Priyanshu1035** [comment]
Kindly close the issue as it is done but not referenced.

**Comment by DaanishShaikh** [comment]
is this issue resolved??

**Comment by halllo2** [comment]
yes
