### ISSUE TITLE
X.com links should be there inplace of twitter links.

### ISSUE THREAD

**Issue by SarthakPaandey** [neutralinojs/neutralinojs.github.io#338]
There is twitter link in the docusaurus.config.js which are not in the latest trend so that should be changed to X links.

**Comment by SarthakPaandey** [comment]
@brakmic @paulocoghi  @Avaray kindly merge this pull request.

**Comment by brakmic** [comment]
@SarthakPaandey,

Not sure why you added me to the list. I am not the maintainer of this repo.
